server:
  port: 8086

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:notification_service}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:notification-service_user}
    password: ${DB_PASSWORD:Password@}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          provider_disables_autocommit: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health,info

notification:
  external:
    appointment-base-url: ${APPOINTMENT_BASE_URL:}
    guest-base-url: ${GUEST_BASE_URL:}
  timezone: Asia/Seoul